// GENERATED FILE — DO NOT EDIT.
// Compiled from src/buildInfo.ts by scripts/build-plugin-lib.js (`make plugin`).
// Edit the TypeScript source and re-run `make plugin`; CI fails if this tree is stale.
"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.BUILD_VERSION = exports.BUILD_TIME = void 0;
// Auto-generated by scripts/gen-build-info.js — do not edit manually
exports.BUILD_TIME = '';
exports.BUILD_VERSION = '0.8.19';
